/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_SimdVectorComputeService */

#ifndef _Included_org_opensearch_knn_jni_SimdVectorComputeService
#define _Included_org_opensearch_knn_jni_SimdVectorComputeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    bulkDistanceCalculation
 * Signature: ([I[FI)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_scoreSimilarityInBulk
  (JNIEnv *, jclass, jintArray, jfloatArray, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    saveSearchContext
 * Signature: ([F[JI)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_saveSearchContext
  (JNIEnv *, jclass, jfloatArray, jlongArray, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    scoreSingleVector
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_scoreSimilarity
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    bulkQuantizedDotProduct
 * Signature: ([B[B[II[FII)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_bulkQuantizedDotProduct
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jintArray, jint, jfloatArray, jint, jint);

/*
 * Class:     org_opensearch_knn_jni_SimdVectorComputeService
 * Method:    bulkQuantizedDotProductKernel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opensearch_knn_jni_SimdVectorComputeService_bulkQuantizedDotProductKernel
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
