//
// Created by Kim, Dooyong on 12/6/24.
//

#ifndef KNNPLUGIN_JNI_INCLUDE_PARTIAL_LOADING_MACROS_H_
#define KNNPLUGIN_JNI_INCLUDE_PARTIAL_LOADING_MACROS_H_

#define PARTIAL_LOADING_INDEX_INPUT_STRATEGY 1
#define PARTIAL_LOADING_INDEX_INPUT_WITH_CACHE_STRATEGY 2
#define PARTIAL_LOADING_MMAP_STRATEGY 3
#define PARTIAL_LOADING_DEBUGGING_VECTOR_STRATEGY 4

#define PARTIAL_LOADING_STRATEGY PARTIAL_LOADING_INDEX_INPUT_STRATEGY

// #define PARTIAL_LOADING_COUT 1

//
// Environment variables for IndexInputWithCacheStorage
//   - PARTIAL_LOADING_IIWC_MAX_BYTES
//

#endif //KNNPLUGIN_JNI_INCLUDE_PARTIAL_LOADING_MACROS_H_
