//
// Created by Kim, Dooyong on 11/29/24.
//

#ifndef KNNPLUGIN_JNI_INCLUDE_PARTIAL_LOADING_MMAP_LINUX_H_
#define KNNPLUGIN_JNI_INCLUDE_PARTIAL_LOADING_MMAP_LINUX_H_

#endif //KNNPLUGIN_JNI_INCLUDE_PARTIAL_LOADING_MMAP_LINUX_H_
